# custom_mcuboot.conf
#CONFIG_BOOT_SWAP_USING_MOVE=y
CONFIG_BOOT_UPGRADE_ONLY=y
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y
CONFIG_BOOT_SIGNATURE_KEY_FILE="/home/halil/myZephyrProjects/nucleo_mcuboot/keys/signing.pem"